// Code generated by mockery v2.42.2. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TransactorMock is an autogenerated mock type for the Transactor type
type TransactorMock struct {
	mock.Mock
}

// WithTx provides a mock function with given fields: ctx, txFn
func (_m *TransactorMock) WithTx(ctx context.Context, txFn func(context.Context) error) error {
	ret := _m.Called(ctx, txFn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, txFn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactorMock creates a new instance of TransactorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactorMock {
	mock := &TransactorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
