# refer https://golangci-lint.run/usage/linters/ for more details on linters

run:
  deadline: 2m
  skip-files:
    - ".*_mock.go$" # skipping generated mock files

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go$
      linters:
        - noctx # excluding as passing context to request is not required in tests
        - funlen # excluding as test functions can be long as they could contain multiple sub tests
        - gochecknoglobals # excluding as using globals in tests is not an issue

linters:
  enable-all: true
  disable:
    - varnamelen
    - goerr113
    - wrapcheck
    - godox
    - exhaustruct
    - ireturn # disabling as it is opinionated
    - sloglint # disabling since we are using different logger
    - zerologlint # disabling since we are using custom logger based on zerolog
    - gochecknoinits # disabling as init functions are required in some cases
    - exhaustivestruct # disabling as it is deprecated
    - golint # disabling as it is deprecated
    - deadcode # disabling as it is deprecated
    - ifshort # disabling as it is deprecated
    - interfacer # disabling as it is deprecated
    - maligned # disabling as it is deprecated
    - nosnakecase # disabling as it is deprecated
    - scopelint # disabling as it is deprecated
    - structcheck # disabling as it is deprecated
    - varcheck # disabling as it is deprecated

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: "log"
            desc: should be replaced with github.com/camelhr/log
          - pkg: "slog"
            desc: should be replaced with github.com/camelhr/log
          - pkg: "logrus"
            desc: should be replaced with github.com/camelhr/log
  nlreturn:
    block-size: 2
  wsl:
    allow-separated-leading-comment: true
  gofmt:
    simplify: true
  nakedret:
    max-func-lines: 0
  errcheck:
    check-type-assertions: true
  gocognit:
    min-function-lines: 15
  gocyclo:
    min-complexity: 10
  revive:
    rules:
      - name: use-any
        disabled: false
      - name: import-alias-naming
        disabled: false
      - name: import-shadowing
        disabled: false
      - name: unused-parameter
        disabled: true
      - name: early-return
        disabled: false
  gocritic:
    enabled-checks:
      - appendAssign
      - argOrder
      - assignOp
      - badCall
      - badCond
      - boolExprSimplify
      - builtinShadow
      - captLocal
      - caseOrder
      - codegenComment
      - commentedOutCode
      - commentedOutImport
      - commentFormatting
      - defaultCaseOrder
      - deprecatedComment
      - docStub
      - dupArg
      - dupBranchBody
      - dupCase
      - dupImport
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - exitAfterDefer
      - flagDeref
      - flagName
      - ifElseChain
      - importShadow
      - mapKey
      - nestingReduce
      - newDeref
      - offBy1
      - ptrToRefParam
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - sloppyTypeAssert
      - stringXbytes
      - switchTrue
      - truncateCmp
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlambda
      - unnecessaryBlock
      - unslice
      - valSwap
      - whyNoLint
      - wrapperFunc
      - yodaStyleExpr
