# refer https://golangci-lint.run/usage/linters/ for more details on linters

run:
  deadline: 2m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files:
    - ".*_mock.go$" # skipping generated mock files
  exclude-rules:
    - path: _test\.go$
      linters:
        - noctx # excluding as passing context to request is not required in tests
        - funlen # excluding as test functions can be long as they could contain multiple sub tests
        - gochecknoglobals # excluding as using globals in tests is not an issue
        - gosec # excluding as it is not required in tests
        - maintidx # excluding as it is not required in tests

linters:
  enable-all: true
  disable:
    - varnamelen
    - wrapcheck
    - godox
    - exhaustruct
    - dupl # disabling as it is failing for repository and service interfaces which are similar
    - tagalign # disabling as it is not compatible with github.com/go-playground/validator/v10
    - ireturn # disabling as it is opinionated
    - sloglint # disabling since we are using different logger
    - zerologlint # disabling since we are using custom logger based on zerolog
    - gochecknoinits # disabling as init functions are required in some cases
    - exhaustivestruct # disabling as it is deprecated
    - golint # disabling as it is deprecated
    - deadcode # disabling as it is deprecated
    - ifshort # disabling as it is deprecated
    - interfacer # disabling as it is deprecated
    - maligned # disabling as it is deprecated
    - nosnakecase # disabling as it is deprecated
    - scopelint # disabling as it is deprecated
    - structcheck # disabling as it is deprecated
    - varcheck # disabling as it is deprecated
    - gomnd # disabling as it is deprecated
    - execinquery # disabling as it is deprecated

linters-settings:
  nlreturn:
    block-size: 2
  wsl:
    allow-separated-leading-comment: true
  gofmt:
    simplify: true
  nakedret:
    max-func-lines: 0
  errcheck:
    check-type-assertions: true
    ignore : "" # https://github.com/golangci/golangci-lint/issues/4733
  gocognit:
    min-function-lines: 15
  gocyclo:
    min-complexity: 10
  tagliatelle:
    case:
      rules:
        json: snake
  interfacebloat:
    max: 15
  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: "log"
            desc: should be replaced with github.com/camelhr/log
          - pkg: "slog"
            desc: should be replaced with github.com/camelhr/log
          - pkg: "logrus"
            desc: should be replaced with github.com/camelhr/log
  revive:
    rules:
      - name: use-any
        disabled: false
      - name: import-alias-naming
        disabled: false
      - name: import-shadowing
        disabled: false
      - name: unused-parameter
        disabled: true
      - name: early-return
        disabled: false
  gocritic:
    enabled-checks:
      - boolExprSimplify
      - builtinShadow
      - commentedOutCode
      - commentedOutImport
      - docStub
      - dupImport
      - emptyFallthrough
      - emptyStringTest
      - importShadow
      - nestingReduce
      - ptrToRefParam
      - stringXbytes
      - truncateCmp
      - typeAssertChain
      - unnecessaryBlock
      - whyNoLint
      - yodaStyleExpr
