with-expecter: true
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
inpackage: true
filename: "{{.InterfaceName | snakecase}}_mock.go"
all: true
packages:
  github.com/camelhr/camelhr-api/internal/database:
  github.com/camelhr/camelhr-api/internal/domains/auth:
  github.com/camelhr/camelhr-api/internal/domains/session:
  github.com/camelhr/camelhr-api/internal/domains/organization:
  github.com/camelhr/camelhr-api/internal/domains/user:
