// Code generated by mockery v2.43.1. DO NOT EDIT.

package user

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateOwner provides a mock function with given fields: ctx, orgID, email, password
func (_m *MockService) CreateOwner(ctx context.Context, orgID int64, email string, password string) (User, error) {
	ret := _m.Called(ctx, orgID, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateOwner")
	}

	var r0 User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) (User, error)); ok {
		return rf(ctx, orgID, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) User); ok {
		r0 = rf(ctx, orgID, email, password)
	} else {
		r0 = ret.Get(0).(User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = rf(ctx, orgID, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOwner'
type MockService_CreateOwner_Call struct {
	*mock.Call
}

// CreateOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID int64
//   - email string
//   - password string
func (_e *MockService_Expecter) CreateOwner(ctx interface{}, orgID interface{}, email interface{}, password interface{}) *MockService_CreateOwner_Call {
	return &MockService_CreateOwner_Call{Call: _e.mock.On("CreateOwner", ctx, orgID, email, password)}
}

func (_c *MockService_CreateOwner_Call) Run(run func(ctx context.Context, orgID int64, email string, password string)) *MockService_CreateOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_CreateOwner_Call) Return(_a0 User, _a1 error) *MockService_CreateOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateOwner_Call) RunAndReturn(run func(context.Context, int64, string, string) (User, error)) *MockService_CreateOwner_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, orgID, email, password
func (_m *MockService) CreateUser(ctx context.Context, orgID int64, email string, password string) (User, error) {
	ret := _m.Called(ctx, orgID, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) (User, error)); ok {
		return rf(ctx, orgID, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) User); ok {
		r0 = rf(ctx, orgID, email, password)
	} else {
		r0 = ret.Get(0).(User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = rf(ctx, orgID, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID int64
//   - email string
//   - password string
func (_e *MockService_Expecter) CreateUser(ctx interface{}, orgID interface{}, email interface{}, password interface{}) *MockService_CreateUser_Call {
	return &MockService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, orgID, email, password)}
}

func (_c *MockService_CreateUser_Call) Run(run func(ctx context.Context, orgID int64, email string, password string)) *MockService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_CreateUser_Call) Return(_a0 User, _a1 error) *MockService_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateUser_Call) RunAndReturn(run func(context.Context, int64, string, string) (User, error)) *MockService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllUsersByOrgID provides a mock function with given fields: ctx, orgID
func (_m *MockService) DeleteAllUsersByOrgID(ctx context.Context, orgID int64) error {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllUsersByOrgID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteAllUsersByOrgID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllUsersByOrgID'
type MockService_DeleteAllUsersByOrgID_Call struct {
	*mock.Call
}

// DeleteAllUsersByOrgID is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID int64
func (_e *MockService_Expecter) DeleteAllUsersByOrgID(ctx interface{}, orgID interface{}) *MockService_DeleteAllUsersByOrgID_Call {
	return &MockService_DeleteAllUsersByOrgID_Call{Call: _e.mock.On("DeleteAllUsersByOrgID", ctx, orgID)}
}

func (_c *MockService_DeleteAllUsersByOrgID_Call) Run(run func(ctx context.Context, orgID int64)) *MockService_DeleteAllUsersByOrgID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_DeleteAllUsersByOrgID_Call) Return(_a0 error) *MockService_DeleteAllUsersByOrgID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteAllUsersByOrgID_Call) RunAndReturn(run func(context.Context, int64) error) *MockService_DeleteAllUsersByOrgID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *MockService) DeleteUser(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockService_DeleteUser_Call {
	return &MockService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockService_DeleteUser_Call) Run(run func(ctx context.Context, id int64)) *MockService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_DeleteUser_Call) Return(_a0 error) *MockService_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteUser_Call) RunAndReturn(run func(context.Context, int64) error) *MockService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DisableUser provides a mock function with given fields: ctx, id, comment
func (_m *MockService) DisableUser(ctx context.Context, id int64, comment string) error {
	ret := _m.Called(ctx, id, comment)

	if len(ret) == 0 {
		panic("no return value specified for DisableUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DisableUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableUser'
type MockService_DisableUser_Call struct {
	*mock.Call
}

// DisableUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - comment string
func (_e *MockService_Expecter) DisableUser(ctx interface{}, id interface{}, comment interface{}) *MockService_DisableUser_Call {
	return &MockService_DisableUser_Call{Call: _e.mock.On("DisableUser", ctx, id, comment)}
}

func (_c *MockService_DisableUser_Call) Run(run func(ctx context.Context, id int64, comment string)) *MockService_DisableUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockService_DisableUser_Call) Return(_a0 error) *MockService_DisableUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DisableUser_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockService_DisableUser_Call {
	_c.Call.Return(run)
	return _c
}

// EnableUser provides a mock function with given fields: ctx, id, comment
func (_m *MockService) EnableUser(ctx context.Context, id int64, comment string) error {
	ret := _m.Called(ctx, id, comment)

	if len(ret) == 0 {
		panic("no return value specified for EnableUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_EnableUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableUser'
type MockService_EnableUser_Call struct {
	*mock.Call
}

// EnableUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - comment string
func (_e *MockService_Expecter) EnableUser(ctx interface{}, id interface{}, comment interface{}) *MockService_EnableUser_Call {
	return &MockService_EnableUser_Call{Call: _e.mock.On("EnableUser", ctx, id, comment)}
}

func (_c *MockService_EnableUser_Call) Run(run func(ctx context.Context, id int64, comment string)) *MockService_EnableUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockService_EnableUser_Call) Return(_a0 error) *MockService_EnableUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_EnableUser_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockService_EnableUser_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAPIToken provides a mock function with given fields: ctx, id
func (_m *MockService) GenerateAPIToken(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAPIToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_GenerateAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAPIToken'
type MockService_GenerateAPIToken_Call struct {
	*mock.Call
}

// GenerateAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) GenerateAPIToken(ctx interface{}, id interface{}) *MockService_GenerateAPIToken_Call {
	return &MockService_GenerateAPIToken_Call{Call: _e.mock.On("GenerateAPIToken", ctx, id)}
}

func (_c *MockService_GenerateAPIToken_Call) Run(run func(ctx context.Context, id int64)) *MockService_GenerateAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_GenerateAPIToken_Call) Return(_a0 error) *MockService_GenerateAPIToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_GenerateAPIToken_Call) RunAndReturn(run func(context.Context, int64) error) *MockService_GenerateAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByAPIToken provides a mock function with given fields: ctx, apiToken
func (_m *MockService) GetUserByAPIToken(ctx context.Context, apiToken string) (User, error) {
	ret := _m.Called(ctx, apiToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByAPIToken")
	}

	var r0 User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (User, error)); ok {
		return rf(ctx, apiToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) User); ok {
		r0 = rf(ctx, apiToken)
	} else {
		r0 = ret.Get(0).(User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, apiToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetUserByAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByAPIToken'
type MockService_GetUserByAPIToken_Call struct {
	*mock.Call
}

// GetUserByAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - apiToken string
func (_e *MockService_Expecter) GetUserByAPIToken(ctx interface{}, apiToken interface{}) *MockService_GetUserByAPIToken_Call {
	return &MockService_GetUserByAPIToken_Call{Call: _e.mock.On("GetUserByAPIToken", ctx, apiToken)}
}

func (_c *MockService_GetUserByAPIToken_Call) Run(run func(ctx context.Context, apiToken string)) *MockService_GetUserByAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetUserByAPIToken_Call) Return(_a0 User, _a1 error) *MockService_GetUserByAPIToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetUserByAPIToken_Call) RunAndReturn(run func(context.Context, string) (User, error)) *MockService_GetUserByAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockService) GetUserByID(ctx context.Context, id int64) (User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockService_GetUserByID_Call {
	return &MockService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockService_GetUserByID_Call) Run(run func(ctx context.Context, id int64)) *MockService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_GetUserByID_Call) Return(_a0 User, _a1 error) *MockService_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetUserByID_Call) RunAndReturn(run func(context.Context, int64) (User, error)) *MockService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByOrgIDEmail provides a mock function with given fields: ctx, orgID, email
func (_m *MockService) GetUserByOrgIDEmail(ctx context.Context, orgID int64, email string) (User, error) {
	ret := _m.Called(ctx, orgID, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByOrgIDEmail")
	}

	var r0 User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (User, error)); ok {
		return rf(ctx, orgID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) User); ok {
		r0 = rf(ctx, orgID, email)
	} else {
		r0 = ret.Get(0).(User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, orgID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetUserByOrgIDEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByOrgIDEmail'
type MockService_GetUserByOrgIDEmail_Call struct {
	*mock.Call
}

// GetUserByOrgIDEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID int64
//   - email string
func (_e *MockService_Expecter) GetUserByOrgIDEmail(ctx interface{}, orgID interface{}, email interface{}) *MockService_GetUserByOrgIDEmail_Call {
	return &MockService_GetUserByOrgIDEmail_Call{Call: _e.mock.On("GetUserByOrgIDEmail", ctx, orgID, email)}
}

func (_c *MockService_GetUserByOrgIDEmail_Call) Run(run func(ctx context.Context, orgID int64, email string)) *MockService_GetUserByOrgIDEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetUserByOrgIDEmail_Call) Return(_a0 User, _a1 error) *MockService_GetUserByOrgIDEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetUserByOrgIDEmail_Call) RunAndReturn(run func(context.Context, int64, string) (User, error)) *MockService_GetUserByOrgIDEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByOrgSubdomainAPIToken provides a mock function with given fields: ctx, orgSubdomain, apiToken
func (_m *MockService) GetUserByOrgSubdomainAPIToken(ctx context.Context, orgSubdomain string, apiToken string) (User, error) {
	ret := _m.Called(ctx, orgSubdomain, apiToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByOrgSubdomainAPIToken")
	}

	var r0 User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (User, error)); ok {
		return rf(ctx, orgSubdomain, apiToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) User); ok {
		r0 = rf(ctx, orgSubdomain, apiToken)
	} else {
		r0 = ret.Get(0).(User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgSubdomain, apiToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetUserByOrgSubdomainAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByOrgSubdomainAPIToken'
type MockService_GetUserByOrgSubdomainAPIToken_Call struct {
	*mock.Call
}

// GetUserByOrgSubdomainAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - orgSubdomain string
//   - apiToken string
func (_e *MockService_Expecter) GetUserByOrgSubdomainAPIToken(ctx interface{}, orgSubdomain interface{}, apiToken interface{}) *MockService_GetUserByOrgSubdomainAPIToken_Call {
	return &MockService_GetUserByOrgSubdomainAPIToken_Call{Call: _e.mock.On("GetUserByOrgSubdomainAPIToken", ctx, orgSubdomain, apiToken)}
}

func (_c *MockService_GetUserByOrgSubdomainAPIToken_Call) Run(run func(ctx context.Context, orgSubdomain string, apiToken string)) *MockService_GetUserByOrgSubdomainAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetUserByOrgSubdomainAPIToken_Call) Return(_a0 User, _a1 error) *MockService_GetUserByOrgSubdomainAPIToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetUserByOrgSubdomainAPIToken_Call) RunAndReturn(run func(context.Context, string, string) (User, error)) *MockService_GetUserByOrgSubdomainAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByOrgSubdomainEmail provides a mock function with given fields: ctx, orgSubdomain, email
func (_m *MockService) GetUserByOrgSubdomainEmail(ctx context.Context, orgSubdomain string, email string) (User, error) {
	ret := _m.Called(ctx, orgSubdomain, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByOrgSubdomainEmail")
	}

	var r0 User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (User, error)); ok {
		return rf(ctx, orgSubdomain, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) User); ok {
		r0 = rf(ctx, orgSubdomain, email)
	} else {
		r0 = ret.Get(0).(User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgSubdomain, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetUserByOrgSubdomainEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByOrgSubdomainEmail'
type MockService_GetUserByOrgSubdomainEmail_Call struct {
	*mock.Call
}

// GetUserByOrgSubdomainEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - orgSubdomain string
//   - email string
func (_e *MockService_Expecter) GetUserByOrgSubdomainEmail(ctx interface{}, orgSubdomain interface{}, email interface{}) *MockService_GetUserByOrgSubdomainEmail_Call {
	return &MockService_GetUserByOrgSubdomainEmail_Call{Call: _e.mock.On("GetUserByOrgSubdomainEmail", ctx, orgSubdomain, email)}
}

func (_c *MockService_GetUserByOrgSubdomainEmail_Call) Run(run func(ctx context.Context, orgSubdomain string, email string)) *MockService_GetUserByOrgSubdomainEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetUserByOrgSubdomainEmail_Call) Return(_a0 User, _a1 error) *MockService_GetUserByOrgSubdomainEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetUserByOrgSubdomainEmail_Call) RunAndReturn(run func(context.Context, string, string) (User, error)) *MockService_GetUserByOrgSubdomainEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ResetAPIToken provides a mock function with given fields: ctx, id
func (_m *MockService) ResetAPIToken(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ResetAPIToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ResetAPIToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetAPIToken'
type MockService_ResetAPIToken_Call struct {
	*mock.Call
}

// ResetAPIToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) ResetAPIToken(ctx interface{}, id interface{}) *MockService_ResetAPIToken_Call {
	return &MockService_ResetAPIToken_Call{Call: _e.mock.On("ResetAPIToken", ctx, id)}
}

func (_c *MockService_ResetAPIToken_Call) Run(run func(ctx context.Context, id int64)) *MockService_ResetAPIToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_ResetAPIToken_Call) Return(_a0 error) *MockService_ResetAPIToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ResetAPIToken_Call) RunAndReturn(run func(context.Context, int64) error) *MockService_ResetAPIToken_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, id, newPassword
func (_m *MockService) ResetPassword(ctx context.Context, id int64, newPassword string) error {
	ret := _m.Called(ctx, id, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - newPassword string
func (_e *MockService_Expecter) ResetPassword(ctx interface{}, id interface{}, newPassword interface{}) *MockService_ResetPassword_Call {
	return &MockService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, id, newPassword)}
}

func (_c *MockService_ResetPassword_Call) Run(run func(ctx context.Context, id int64, newPassword string)) *MockService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockService_ResetPassword_Call) Return(_a0 error) *MockService_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ResetPassword_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SetEmailVerified provides a mock function with given fields: ctx, id
func (_m *MockService) SetEmailVerified(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetEmailVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_SetEmailVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEmailVerified'
type MockService_SetEmailVerified_Call struct {
	*mock.Call
}

// SetEmailVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) SetEmailVerified(ctx interface{}, id interface{}) *MockService_SetEmailVerified_Call {
	return &MockService_SetEmailVerified_Call{Call: _e.mock.On("SetEmailVerified", ctx, id)}
}

func (_c *MockService_SetEmailVerified_Call) Run(run func(ctx context.Context, id int64)) *MockService_SetEmailVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockService_SetEmailVerified_Call) Return(_a0 error) *MockService_SetEmailVerified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_SetEmailVerified_Call) RunAndReturn(run func(context.Context, int64) error) *MockService_SetEmailVerified_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
