name: Build

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO_REGISTRY: ghcr.io/${{ github.repository_owner }}/camelhr
      IMAGE_NAME: camelhr-api
    steps:
      - uses: actions/checkout@v4

      - name: login to github docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build & publish docker image
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: |
          docker build \
            -t $GITHUB_REPO_REGISTRY/$IMAGE_NAME:${GITHUB_REF##*/} \
            -t $GITHUB_REPO_REGISTRY/$IMAGE_NAME:$COMMIT_SHA \
            -t $GITHUB_REPO_REGISTRY/$IMAGE_NAME:latest .
            docker push -a $GITHUB_REPO_REGISTRY/$IMAGE_NAME
