name: Deploy on Free Plan

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: 
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    container: ghcr.io/camelhr/camelhr/camelhr-api:latest
    steps:
      - name: run database migrations
        env:
          DB_CONN: ${{ secrets.DB_CONN_STRING }}
        run: |
          cd /app
          ./dbmigrator up

  deoploy-render:
    runs-on: ubuntu-latest
    steps:
      - name: trigger deploy on render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
